language: python

# Use container-based infrastructure
sudo: false

# Test environments
matrix:
  include:
    - env: TOXENV=py27-wt10
    - env: TOXENV=py33-wt10
    - env: TOXENV=py34-wt10
    - env: TOXENV=py35-wt10
      python: 3.5
    - env: TOXENV=py27-wt11
    - env: TOXENV=py33-wt11
    - env: TOXENV=py34-wt11
    - env: TOXENV=py35-wt11
      python: 3.5
    - env: TOXENV=py27-wt12
    - env: TOXENV=py33-wt12
    - env: TOXENV=py34-wt12
    - env: TOXENV=py35-wt12
      python: 3.5
    - env: TOXENV=flake8

# Package installation
install:
  - pip install tox coveralls

# Run tests
script:
  - tox

# Call subsequent services
after_success:
  - coveralls
